"""solve issues active flag to sites-166,add filter on api read-173

Revision ID: 2c4f7a98a591
Revises: 7a32241916f7
Create Date: 2024-11-28 15:58:26.149239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4f7a98a591'
down_revision = '7a32241916f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
