"""Add client-user relationship

Revision ID: 3c765af43b5a
Revises: 81278a3571b2
Create Date: 2025-03-19 13:34:08.803237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c765af43b5a'
down_revision = '81278a3571b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_uuid', sa.UUID(), nullable=True, comment='The foreign key to the clients table'))
    op.create_foreign_key(None, 'users', 'clients', ['client_uuid'], ['client_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'client_uuid')
    # ### end Alembic commands ###
