"""set nullable of horizon_minute to False and add a default value -1

Revision ID: 42f8f283e2c9
Revises: fa74fbe945fd
Create Date: 2025-02-26 00:42:53.216590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f8f283e2c9'
down_revision = 'fa74fbe945fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecast_values', 'horizon_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('-1'),
               nullable=False,
               existing_comment='The time difference between the creation time of the forecast value and the start of the time interval it applies for')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecast_values', 'horizon_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True,
               existing_comment='The time difference between the creation time of the forecast value and the start of the time interval it applies for')
    # ### end Alembic commands ###
