"""add n-n locations relationship

Revision ID: 6aa3e123ea5a
Revises: 12c0ccf6b826
Create Date: 2025-07-10 16:27:54.945962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa3e123ea5a'
down_revision = '12c0ccf6b826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_locations',
    sa.Column('location_location_uuid', sa.UUID(), nullable=False),
    sa.Column('location_child_uuid', sa.UUID(), nullable=False, comment='The foreign key to the locations table'),
    sa.Column('location_parent_uuid', sa.UUID(), nullable=False, comment='The foreign key to the locations table'),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_child_uuid'], ['locations.location_uuid'], ),
    sa.ForeignKeyConstraint(['location_parent_uuid'], ['locations.location_uuid'], ),
    sa.PrimaryKeyConstraint('location_location_uuid'),
    sa.UniqueConstraint('location_child_uuid', 'location_parent_uuid', name='idx_location_location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_locations')
    # ### end Alembic commands ###
