"""Fix migration

Revision ID: 7731b672d8ae
Revises: 2c4f7a98a591
Create Date: 2024-11-28 16:03:45.151598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7731b672d8ae'
down_revision = '2c4f7a98a591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
