"""solve issues active flag to sites-166,add filter on api read-173

Revision ID: 7a32241916f7
Revises: 92172b9903cc
Create Date: 2024-11-28 15:55:00.655261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a32241916f7'
down_revision = '575f99caf2d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'active',
               existing_type=sa.BOOLEAN(),
               comment='Indicates if site is active',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates if site is active',
               existing_nullable=True)
    # ### end Alembic commands ###
