"""Add probabilistic_values column to forecast value table

Revision ID: 81278a3571b2
Revises: 42f8f283e2c9
Create Date: 2025-03-08 12:57:24.464340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "81278a3571b2"
down_revision = "42f8f283e2c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forecast_values",
        sa.Column(
            "probabilistic_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
            comment="Probabilistic forecast values, like p10, p50, p90",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forecast_values", "probabilistic_values")
    # ### end Alembic commands ###
