"""solve issues active flag to sites-166,add filter on api read-173

Revision ID: 92172b9903cc
Revises: ee514b583fa3
Create Date: 2024-11-28 15:43:49.367968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92172b9903cc'
down_revision = 'ee514b583fa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('ml_model_uuid', sa.UUID(), nullable=True, comment='The ML Model which should be used for this site'))
    op.create_foreign_key(None, 'sites', 'ml_model', ['ml_model_uuid'], ['model_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'ml_model_uuid')
    op.drop_column('sites', 'active')
    # ### end Alembic commands ###
