"""Fix migration

Revision ID: 9df605a0d04f
Revises: c5faca90552c
Create Date: 2024-11-28 16:08:36.348172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df605a0d04f'
down_revision = 'c5faca90552c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
