"""set horizon_minute nullable

Revision ID: bbdbcedc6b24
Revises: fa74fbe945fd
Create Date: 2025-01-30 17:29:51.814972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdbcedc6b24'
down_revision = 'fa74fbe945fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
