"""Fix migration

Revision ID: c5faca90552c
Revises: 7731b672d8ae
Create Date: 2024-11-28 16:04:05.811363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5faca90552c'
down_revision = '7731b672d8ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
