"""site history table

Revision ID: c8ef88c250e7
Revises: d5c9e13a8b66
Create Date: 2024-11-29 22:42:25.535162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8ef88c250e7'
down_revision = '7a32241916f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_sites',
    sa.Column('site_history_uuid', sa.UUID(), nullable=False),
    sa.Column('site_uuid', sa.UUID(), nullable=False, comment='The site which this history record relates to'),
    sa.Column('site_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='A snapshot of the site record as JSONB'),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('operation_type', sa.TEXT(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('site_history_uuid')
    )
    op.create_index(op.f('ix_h_sites_site_uuid'), 'h_sites', ['site_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_h_sites_site_uuid'), table_name='h_sites')
    op.drop_table('h_sites')
    # ### end Alembic commands ###
