"""Add ml models to site table

Revision ID: d5c9e13a8b66
Revises: ea0672033541
Create Date: 2024-11-25 16:43:59.745411

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5c9e13a8b66"
down_revision = "ea0672033541"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key(None, "forecast_values", "ml_model", ["ml_model_uuid"], ["model_uuid"])
    op.add_column(
        "sites",
        sa.Column(
            "ml_model_uuid",
            sa.UUID(),
            nullable=True,
            comment="The ML Model which should be used for this site",
        ),
    )
    op.create_foreign_key(None, "sites", "ml_model", ["ml_model_uuid"], ["model_uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sites", type_="foreignkey")
    op.drop_column("sites", "ml_model_uuid")
    op.drop_constraint(None, "forecast_values", type_="foreignkey")
    # ### end Alembic commands ###
