"""Add service level to site group

Revision ID: ea0672033541
Revises: 31d501a0aa52
Create Date: 2024-11-18 13:29:03.441894

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ea0672033541"
down_revision = "31d501a0aa52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_groups",
        sa.Column(
            "service_level",
            sa.Integer(),
            nullable=True,
            comment="The service level of the site group. 0 is free1 is paid",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_groups", "service_level")
    # ### end Alembic commands ###
