"""solve issues active flag to sites-166,add filter on api read-173

Revision ID: ee514b583fa3
Revises: 575f99caf2d4
Create Date: 2024-11-25 21:03:53.162405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee514b583fa3'
down_revision = '575f99caf2d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
