"""Add description column to MLModelSQL

Revision ID: fa74fbe945fd
Revises: 12c0ccf6b825
Create Date: 2025-01-19 18:19:45.306091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa74fbe945fd'
down_revision = '12c0ccf6b825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model', sa.Column('description', sa.String(), server_default='No description provided.', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_model', 'description')
    # ### end Alembic commands ###
