"""Add timestamp_utc column to forecasts table

Revision ID: 830bec1172a8
Revises: 4e1eb8b4e7f2
Create Date: 2023-02-23 22:15:18.563516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '830bec1172a8'
down_revision = '4e1eb8b4e7f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_values_site_uuid', table_name='forecast_values')
    op.drop_constraint('forecast_values_site_uuid_fkey', 'forecast_values', type_='foreignkey')
    op.drop_column('forecast_values', 'site_uuid')
    op.add_column('forecasts', sa.Column('timestamp_utc', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_forecasts_timestamp_utc'), 'forecasts', ['timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_timestamp_utc'), table_name='forecasts')
    op.drop_column('forecasts', 'timestamp_utc')
    op.add_column('forecast_values', sa.Column('site_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('forecast_values_site_uuid_fkey', 'forecast_values', 'sites', ['site_uuid'], ['site_uuid'])
    op.create_index('ix_forecast_values_site_uuid', 'forecast_values', ['site_uuid'], unique=False)
    # ### end Alembic commands ###
