name: Default Branch Push CI

on:
  push:
    branches: [ "main" ]

jobs:
  merged-ci:
    uses: openclimatefix/.github/.github/workflows/default_branch_pr_merged_ci.yml@main
    secrets: inherit
    with:
      containerfile: None
      enable_pypi: true



